sylius_theme:
    sources:
        filesystem:
            scan_depth: 1
            directories:
                - "%kernel.project_dir%/themes"
#    use_parent_assets: true

when@test: &sylius_theme_test
    sylius_theme:
        sources:
            test: ~

when@test_cached: *sylius_theme_test
