#sylius_shop:
#    resource: "@SyliusShopBundle/Resources/config/routing.yml"
#    prefix: /{_locale}
#    requirements:
#        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

# ------------------------------------------------------------
# English shop (default language)
# No URL prefix → https://airsoftlabs.eu/
# ------------------------------------------------------------
sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"
    prefix: /
    defaults:
        _locale: en_US


# ------------------------------------------------------------
# Dutch shop
# URL prefix → https://airsoftlabs.eu/nl/
# ------------------------------------------------------------
sylius_shop_nl:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"
    prefix: /nl
    defaults:
        _locale: nl_NL
        
sylius_shop_payum:
    resource: "@SyliusPayumBundle/Resources/config/routing/integrations/sylius_shop.yaml"

sylius_payment_notify:
    resource: "@SyliusPaymentBundle/Resources/config/routing/integrations/sylius.yaml"

#sylius_shop_default_locale:
#    path: /
#    methods: [GET]
#    defaults:
#        _controller: sylius_shop.controller.locale_switch::switchAction
        
sylius_shop_default_locale:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius_shop.controller.locale_switch::switchAction
        _locale: en_US  # default locale without prefix

sylius_shop_secondary_locale:
    path: /nl/
    methods: [GET]
    defaults:
        _controller: sylius_shop.controller.locale_switch::switchAction
        _locale: nl_NL  # secondary locale

# see https://web.dev/change-password-url/
sylius_shop_request_password_reset_token_redirect:
    path: /.well-known/change-password
    methods: [GET]
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: sylius_shop_request_password_reset_token
        permanent: false
